# Generated by Django 4.1.4 on 2022-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owner_chat_id',
            field=models.CharField(default='2034382543', max_length=200, unique=True, verbose_name='ID telegram аккаунта ботовода'),
            preserve_default=False,
        ),
    ]
