# Generated by Django 4.1.4 on 2022-12-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_owner_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unhashed_password',
            field=models.CharField(default='srd6tfyugbijhvgc', max_length=20),
            preserve_default=False,
        ),
    ]
