# Generated by Django 4.1.4 on 2022-12-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_unhashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_rate',
            field=models.BooleanField(default=True, verbose_name='Бесплатный тариф'),
        ),
    ]
