# Generated by Django 4.1.4 on 2022-12-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_free_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='free_rate',
            new_name='is_free_rate',
        ),
    ]
