# Generated by Django 4.1.4 on 2022-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_add_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='faq_url',
            field=models.URLField(default='https://youtube.com'),
            preserve_default=False,
        ),
    ]
