# Generated by Django 4.1.4 on 2022-12-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_botquestionmodel_answersvariantforbotquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botquestionmodel',
            options={'ordering': ('-priority',), 'verbose_name': 'Вопрос от бота', 'verbose_name_plural': 'Серия вопросов бота'},
        ),
    ]
