# Generated by Django 4.1.4 on 2022-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_alter_botquestionmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='start_message_button_text',
            field=models.CharField(default='Начать', max_length=100),
            preserve_default=False,
        ),
    ]
