# Generated by Django 4.1.4 on 2022-12-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_botmessagessettingsmodel_start_message_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('current_condition', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
