# Generated by Django 4.1.4 on 2022-12-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_telegramusercondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUserCondition',
            new_name='TelegramUserConditionModel',
        ),
    ]
