# Generated by Django 4.1.4 on 2022-12-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_rename_current_condition_telegramuserconditionmodel_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuserconditionmodel',
            name='condition_counter',
            field=models.IntegerField(default=0),
        ),
    ]
