# Generated by Django 4.1.4 on 2022-12-16 02:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_alter_botquestionmodel_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersvariantforbotquestionmodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='botquestionmodel',
            name='messages_settings',
        ),
        migrations.DeleteModel(
            name='TelegramUserConditionModel',
        ),
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='first_question_buttons_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['test', 'test'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='first_question_text',
            field=models.TextField(default='why?', max_length=4000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswersVariantForBotQuestionModel',
        ),
        migrations.DeleteModel(
            name='BotQuestionModel',
        ),
    ]
