# Generated by Django 4.1.4 on 2022-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_remove_answersvariantforbotquestionmodel_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='second_question_text',
            field=models.TextField(default='input', max_length=4000),
            preserve_default=False,
        ),
    ]
