# Generated by Django 4.1.4 on 2022-12-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_botmessagessettingsmodel_second_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='third_question_text',
            field=models.TextField(default='3 input', max_length=4000),
            preserve_default=False,
        ),
    ]
