# Generated by Django 4.1.4 on 2022-12-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_botmessagessettingsmodel_third_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='after_data_loading_text',
            field=models.TextField(default='Спасибо за ваши ответы. Укажите ваш номер телефона или ник в телеграм, чтобы получить подробный разбор вашей ситуации с пошаговыми рекомендациями. Что будет после того, как вы укажете свой номер? Я позвоню вам и мы договоримся о созвоне в скайпе или зуме. Подробно проанализируем ваш проект и составим план по решению задач, которые вы описали ранее. Ваш номер телефона или ник в телеграм:', max_length=4000),
            preserve_default=False,
        ),
    ]
