# Generated by Django 4.1.4 on 2022-12-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0014_telegrambotclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramBotClient',
            new_name='TelegramBotClientModel',
        ),
    ]
