# Generated by Django 4.1.4 on 2022-12-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0015_rename_telegrambotclient_telegrambotclientmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotclientmodel',
            name='first_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telegrambotclientmodel',
            name='phone_number_or_nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telegrambotclientmodel',
            name='second_answer',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='telegrambotclientmodel',
            name='third_answer',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
