# Generated by Django 4.1.4 on 2022-12-17 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tg_bot', '0016_alter_telegrambotclientmodel_first_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotclientmodel',
            name='free_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegrambotclientmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
