# Generated by Django 4.1.4 on 2022-12-17 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tg_bot', '0017_telegrambotclientmodel_free_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
