# Generated by Django 4.1.4 on 2022-12-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0018_botmessagessettingsmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotclientmodel',
            old_name='phone_number_or_nickname',
            new_name='phone_or_nickname',
        ),
    ]
