# Generated by Django 4.1.4 on 2022-12-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0021_botmessagessettingsmodel_bot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='user_inactive_for_hour_message_text',
            field=models.TextField(default='К сожалению наш диалог был прерван. Если у вас возникли какие-либо вопросы, пожалуйста, оставьте ваш номер телефона или ник в телеграм, чтобы я мог связаться с вами и ответить на них. Ваш номер телефона или ник в телеграм:', max_length=4000),
            preserve_default=False,
        ),
    ]
