# Generated by Django 4.1.4 on 2022-12-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0022_botmessagessettingsmodel_user_inactive_for_hour_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotclientmodel',
            name='request_sent',
            field=models.BooleanField(default=False, verbose_name='Заявка успешно отправлено'),
        ),
    ]
