# Generated by Django 4.1.4 on 2022-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0024_rename_user_inactive_for_hour_message_text_botmessagessettingsmodel_user_inactive_for_hour_message_t'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmessagessettingsmodel',
            old_name='user_inactive_for_hour_message_text_for_input',
            new_name='user_inactive_for_hour_message_text_first_part',
        ),
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='user_inactive_for_hour_message_text_second_part',
            field=models.TextField(default='Предлагаю вам ознакомиться с бизнес кейсом моего клиента, которому я помог заработать 2500 евро за 7 дней.', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessagessettingsmodel',
            name='user_inactive_for_hour_message_text_second_part_inline_link',
            field=models.URLField(default='https://youtube.com'),
            preserve_default=False,
        ),
    ]
