# Generated by Django 4.1.4 on 2022-12-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0025_rename_user_inactive_for_hour_message_text_for_input_botmessagessettingsmodel_user_inactive_for_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotclientmodel',
            old_name='message_for_on_hour_inactive_sent',
            new_name='message_for_one_hour_inactive_sent',
        ),
    ]
