# Generated by Django 4.1.4 on 2022-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0026_rename_message_for_on_hour_inactive_sent_telegrambotclientmodel_message_for_one_hour_inactive_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotclientmodel',
            name='message_for_one_hour_inactive_sent',
        ),
        migrations.RemoveField(
            model_name='telegrambotclientmodel',
            name='request_sent',
        ),
        migrations.AddField(
            model_name='telegrambotclientmodel',
            name='sent_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
