# Generated by Django 4.1.4 on 2022-12-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0027_remove_telegrambotclientmodel_message_for_one_hour_inactive_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotclientmodel',
            old_name='sent_message_count',
            new_name='sent_messages_for_inactive_count',
        ),
    ]
