# Generated by Django 4.1.4 on 2022-12-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0033_alter_telegrambotclientmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotclientmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='telegrambotclientmodel',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tg_bot.botmessagessettingsmodel'),
            preserve_default=False,
        ),
    ]
