# Generated by Django 4.1.4 on 2022-12-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0036_telegrambotclientmodel_bot_wait_input_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotclientmodel',
            old_name='bot',
            new_name='bots',
        ),
        migrations.AlterField(
            model_name='telegrambotclientmodel',
            name='bot_wait_input_username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Имя бота, который ждёт входные данные'),
        ),
    ]
