# Generated by Django 4.1.4 on 2022-12-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0037_rename_bot_telegrambotclientmodel_bots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotclientmodel',
            name='last_message_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='ID последнего сообщения'),
        ),
    ]
