# Generated by Django 4.1.4 on 2022-12-21 23:13

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0038_telegrambotclientmodel_last_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessagessettingsmodel',
            name='first_question_buttons_text',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
