# Generated by Django 4.1.4 on 2022-12-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0040_alter_botmessagessettingsmodel_first_question_buttons_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotclientmodel',
            name='bot_wait_input_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя бота, который ждёт входные данные'),
        ),
    ]
