# Generated by Django 4.1.4 on 2022-12-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0041_alter_telegrambotclientmodel_bot_wait_input_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotclientmodel',
            name='free_rate',
        ),
    ]
