# Generated by Django 4.1.4 on 2022-12-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0042_remove_telegrambotclientmodel_free_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotclientmodel',
            options={'verbose_name': 'Настройкаи твоего бота', 'verbose_name_plural': 'Настройки твоих ботов'},
        ),
    ]
