# Generated by Django 4.1.4 on 2022-12-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0043_alter_telegrambotclientmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmessagessettingsmodel',
            options={'verbose_name': 'Настройки твоего бота', 'verbose_name_plural': 'Настройки твоих ботов'},
        ),
        migrations.AlterModelOptions(
            name='telegrambotclientmodel',
            options={'verbose_name': 'Данные клиента твоего бота', 'verbose_name_plural': 'Данные клиентов твоих ботов'},
        ),
    ]
