# Generated by Django 4.1.4 on 2022-12-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0044_alter_botmessagessettingsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessagessettingsmodel',
            name='second_question_text',
            field=models.TextField(max_length=4000, verbose_name='Текст второго вопроса'),
        ),
    ]
